# Generated by Django 4.2.7 on 2024-02-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_reference', models.CharField(max_length=100)),
                ('period', models.FloatField()),
                ('data_value', models.IntegerField()),
                ('suppressed', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('magnitude', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('Series_title_1', models.CharField(max_length=100)),
                ('Series_title_2', models.CharField(max_length=100)),
                ('Series_title_3', models.CharField(max_length=100)),
            ],
        ),
    ]
