# Generated by Django 4.2.7 on 2024-02-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_businessemployment_data_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessemployment',
            name='data_value',
            field=models.CharField(max_length=100),
        ),
    ]
